In [1]:
import numpy as np

# sum 

In [2]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
test_array.sum(dtype=np.float)

55.0

# axis

In [4]:
axis_array = np.arange(1,13).reshape(3,4)
axis_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
axis_array.sum()

78

In [10]:
axis_array.sum(axis=1), axis_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [11]:
third_order_tensor = np.array([axis_array,axis_array,axis_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [12]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [13]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [14]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

# concatenate

In [15]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [16]:
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [18]:
c = np.array([[1,2,3]])
d = np.array([[4,5,6]])
np.concatenate((c,d), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
e = np.array([[1,2], [3,4]])
f = np.array([[5,6]])
np.concatenate((e,f.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])