In [1]:
import numpy as np

# Operations b/t arrays

In [2]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [3]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [4]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

# Dot product

In [6]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [7]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

# broadcasting

In [8]:
test_matrix = np.array([[1,2,3],[4,5,6]],float)
scalar = 3

In [9]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])