In [1]:
import numpy as np

# 1 all & any

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
np.any(a>5), np.any(a<0)

(True, False)

In [5]:
np.all(a>5), np.all(a<10)

(False, True)

# np.where

In [6]:
np.where(a > 0, 3, 2) # where(condition, TRUE, FALSE)

array([2, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
np.where(a > 4)

(array([5, 6, 7, 8, 9], dtype=int64),)

# argmax & argmin

In [12]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [14]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1], dtype=int64), array([0, 0, 2, 2], dtype=int64))