In [2]:
import numpy as np

#  boolean index

In [3]:
test_array = np.array([1,4,0,2,3,8,9,7],float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [4]:
test_array[test_array>3]

array([4., 8., 9., 7.])

In [5]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [6]:
A = np.array([[12,13,14,12,16,14,11,10,9],
             [11,14,12,15,15,16,10,12,11],
             [10,12,12,15,14,16,10,12,12],
             [19,11,16,14,10,14,11,10,9],
             [12,13,14,12,16,14,11,10,9],
             [12,13,14,12,16,14,11,10,9],
             [12,13,14,12,16,14,11,10,9],
             [12,13,14,12,16,14,11,10,9],
             [12,13,14,12,16,14,11,10,9]])
B = A < 15
B.astype(np.int)

array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 1, 1, 1]])

# fancy index

In [7]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) # 반드시 integer로 선언
a[b] #bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

In [9]:
a.take(b) #bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [10]:
c = np.array([[1,4], [9,16]], float)
d = np.array([0,0,1,1,0], int)
e = np.array([0,1,1,1,1], int)
c[d,e]

array([ 1.,  4., 16., 16.,  4.])